# Generated by Django 2.2.2 on 2019-06-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofileinfo_indiceslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='indicesList',
            field=models.CharField(default="'NDVI':((nir-r)/(nir+r))", max_length=20000),
        ),
    ]
