# Generated by Django 2.2.2 on 2019-06-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190613_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='indicesList',
            field=models.CharField(default='NDVI:((nir-r)/(nir+r))', max_length=20000),
        ),
    ]
