# Generated by Django 2.2.2 on 2019-06-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190613_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='satelliteMetadataFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
